language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vanausloos/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vanausloos/react-test npm teste

after_success:
  - docker build -t vanausloos/multi-client ./client
  - docker build -t vanausloos/multi-nginx ./nginx
  - docker build -t vanausloos/multi-server ./server
  - docker build -t vanausloos/multi-worker ./worker
